<li><img src="./images/artists/Barot_Bellingham_tn.jpg" alt="Barot Bellingham"></li>
<li><img src="./images/artists/Constance_Smith_tn.jpg" alt="Constance Smith"></li>
<li><img src="images/artists/Hassum_Harrod_tn.jpg" alt="Hassum Harrod"></li>
<li><img src="images/artists/Hillary_Goldwynn_tn.jpg" alt="Hillary Goldwynn"></li>
<li><img src="images/artists/Jennifer_Jerome_tn.jpg" alt="Jennifer Jerome"></li>
<li><img src="images/artists/Jonathan_Ferrar_tn.jpg" alt="Jonathan Ferrar"></li>
<li><img src="images/artists/LaVonne_LaRue_tn.jpg" alt="LaVonne LaRue"></li>
<li><img src="./images/artists/Riley_Rewington_tn.jpg" alt="Riley Rewington"></li>
<li><img src="./images/artists/Xhou_Ta_tn.jpg" alt="Xhou Ta"></li>